<a href="https://colab.research.google.com/github/joshi07saurabh/Prediction-of-Fashion-MNIST-dataset/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import keras

Load Dataset

In [ ]:
(X_train,y_train),(X_test,y_test)=keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [ ]:
X_train.shape,y_train.shape

((60000, 28, 28), (60000,))

In [ ]:
X_test.shape,y_test.shape

((10000, 28, 28), (10000,))

Change the dimension of Image

In [ ]:
X_train=np.expand_dims(X_train,-1)
X_train.ndim

4

In [ ]:
X_test=np.expand_dims(X_test,-1)
X_test.ndim

4

Feature Scaling

In [ ]:
X_train=X_train/255
X_test=X_test/255
X_train[0]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val=train_test_split(X_train,y_train,test_size=0.2,random_state=2020)

In [ ]:
X_train.shape

(48000, 28, 28, 1)

CNN model Building


In [ ]:
model=keras.models.Sequential([
                         keras.layers.Conv2D(filters=32,kernel_size=3,strides=(1,1),padding='valid',activation='relu',input_shape=[28,28,1]),
                         keras.layers.MaxPooling2D(pool_size=(2,2)),
                         keras.layers.Flatten(),
                         keras.layers.Dense(units=128,activation='relu'),
                         keras.layers.Dense(units=10,activation='softmax')
])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 13, 13, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 5408)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               692352    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 693,962
Trainable params: 693,962
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics='accuracy')
model.fit(X_train,y_train,epochs=10,batch_size=512,verbose=1,validation_data=(X_val,y_val))

Epoch 1/10
94/94 [==============================] - 19s 198ms/step - loss: 0.9304 - accuracy: 0.6989 - val_loss: 0.4220 - val_accuracy: 0.8512
Epoch 2/10
94/94 [==============================] - 18s 193ms/step - loss: 0.3910 - accuracy: 0.8643 - val_loss: 0.3768 - val_accuracy: 0.8720
Epoch 3/10
94/94 [==============================] - 18s 192ms/step - loss: 0.3418 - accuracy: 0.8812 - val_loss: 0.3382 - val_accuracy: 0.8828
Epoch 4/10
94/94 [==============================] - 18s 192ms/step - loss: 0.3123 - accuracy: 0.8905 - val_loss: 0.3140 - val_accuracy: 0.8905
Epoch 5/10
94/94 [==============================] - 18s 191ms/step - loss: 0.2883 - accuracy: 0.8991 - val_loss: 0.3025 - val_accuracy: 0.8943
Epoch 6/10
94/94 [==============================] - 18s 193ms/step - loss: 0.2604 - accuracy: 0.9099 - val_loss: 0.2975 - val_accuracy: 0.8955
Epoch 7/10
94/94 [==============================] - 18s 192ms/step - loss: 0.2523 - accuracy: 0.9091 - val_loss: 0.2907 - val_accuracy: 0.8976

test the model

In [ ]:
model.predict(np.expand_dims(X_test[0],axis=0)).round(2)

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.98]],
      dtype=float32)

In [ ]:
np.argmax(model.predict(np.expand_dims(X_test[0],axis=0)).round(2))

9

In [ ]:
y_test[0]

9

In [ ]:
y_pred=model.predict(X_test).round(2)

In [ ]:
y_pred

array([[0.  , 0.  , 0.  , ..., 0.01, 0.  , 0.98],
       [0.  , 0.  , 1.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 0.99, 0.  ],
       [0.  , 1.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.01, ..., 0.2 , 0.07, 0.  ]], dtype=float32)

In [ ]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 2s 6ms/step - loss: 0.2788 - accuracy: 0.9002


[0.27877023816108704, 0.9002000093460083]

The accuray of our model is 90%